### ISSUE TITLE
Hello,your site is not avaliable~

### ISSUE THREAD

**Issue by wamdy** [baloise/eZooKeeper#8] opened 2020-02-27 05:05 UTC

**Comment by Tiliavir** [comment] 2020-02-27 13:15
Hi @wamdy,
what site do you refer to? Could you provide some more information?
Thanks for a short update,
Markus

**Comment by MarkusTiede** [comment] 2020-02-28 07:31
Broken builds have been fixed with 6d0af4bd1bafbc9b5cf2e6ff416e70d803392036

**Comment by Tiliavir** [comment] 2020-03-06 09:44
Closed due to lack of further information.

**Comment by wamdy** [comment] 2020-03-07 10:03
I can‘t visit the eclipse plugin update site. http://www.massedynamic.org/eclipse/zookeeper
it returned that:

```
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
```

**Comment by MarkusTiede** [comment] 2020-03-09 15:18
Hi @wamdy - thanks for noticing: the project has been (in the not-recent past) transferred / donated to us.

As far as I know there is currently (no longer) a public update site with pre-compiled binarys / p2-dependencies available. 

At the moment you can / have to do that manually e.g. by cloning and building locally:

Something like this could work
```
git clone https://github.com/baloise/eZooKeeper.git && cd eZooKeeper && mvn clean verify
```

After that you should find the p2-Repo within `org.massedynamic.eclipse.zookeeper.repo/target/repository`

Hope that helps a bit. We need to implement #6 for a proper resolution of this issue.

**Comment by MarkusTiede** [comment] 2020-03-12 11:41
Hence resolving as duplicate of #6. 

@wamdy : did you had any chance to check whether the proposed local workaround is sufficient for you?

**Closed as completed by MarkusTiede** 2020-03-12 11:41 UTC
Labels: help wanted
